# Telecomm Customer Churn

This data set provides information to help you predict what behavior will help you to retain customers. You can analyze all relevant customer data and develop focused customer retention programs.

It is requested a model to predict customer churn. Customers who left within the last month – the column is called Churn

Dataset: https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv

- Use Logistical Regression to build your model
- Features: 'tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip'

In [1]:
import pandas as pd
import pylab as pl
import numpy as np
import scipy.optimize as opt
from sklearn import preprocessing
%matplotlib inline 
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report
from sklearn.metrics import jaccard_score
from sklearn.metrics import log_loss

In [2]:
df = pd.read_csv('https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/ChurnData.csv')
print(df.shape)
df.head()

(200, 28)


tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...    pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...      1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...      0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...      0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...      1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...      0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [3]:
print(df.dtypes)
df.describe()

tenure      float64
age         float64
address     float64
income      float64
ed          float64
employ      float64
equip       float64
callcard    float64
wireless    float64
longmon     float64
tollmon     float64
equipmon    float64
cardmon     float64
wiremon     float64
longten     float64
tollten     float64
cardten     float64
voice       float64
pager       float64
internet    float64
callwait    float64
confer      float64
ebill       float64
loglong     float64
logtoll     float64
lninc       float64
custcat     float64
churn       float64
dtype: object


tenure         age     address       income         ed     employ  \
count  200.000000  200.000000  200.000000   200.000000  200.00000  200.00000   
mean    35.505000   41.165000   11.650000    75.130000    2.82500   10.22500   
std     21.640971   13.076803   10.158419   128.430468    1.28555    8.95743   
min      1.000000   19.000000    0.000000     9.000000    1.00000    0.00000   
25%     16.750000   31.000000    3.000000    31.000000    2.00000    3.00000   
50%     33.500000   40.000000    9.000000    48.000000    3.00000    7.50000   
75%     55.250000   51.000000   18.000000    80.000000    4.00000   17.00000   
max     72.000000   76.000000   48.000000  1668.000000    5.00000   44.00000   

            equip    callcard    wireless    longmon     ...           pager  \
count  200.000000  200.000000  200.000000  200.00000     ...      200.000000   
mean     0.425000    0.705000    0.290000   11.78925     ...        0.275000   
std      0.495584    0.457187    0.454901    9.88725     ...        0.447635   
min      0.000000    0.000000    0.000000    1.10000     ...        0.000000   
25%      0.000000    0.000000    0.000000    5.53750     ...        0.000000   
50%      0.000000    1.000000    0.000000    8.25000     ...        0.000000   
75%      1.000000    1.000000    1.000000   14.30000     ...        1.000000   
max      1.000000    1.000000    1.000000   62.30000     ...        1.000000   

         internet   callwait      confer       ebill     loglong     logtoll  \
count  200.000000  200.00000  200.000000  200.000000  200.000000  200.000000   
mean     0.440000    0.45500    0.460000    0.440000    2.193285    3.229185   
std      0.497633    0.49922    0.499648    0.497633    0.731282    0.281019   
min      0.000000    0.00000    0.000000    0.000000    0.095000    1.749000   
25%      0.000000    0.00000    0.000000    0.000000    1.711750    3.226500   
50%      0.000000    0.00000    0.000000    0.000000    2.110000    3.240000   
75%      1.000000    1.00000    1.000000    1.000000    2.660000    3.240000   
max      1.000000    1.00000    1.000000    1.000000    4.132000    4.227000   

            lninc     custcat       churn  
count  200.000000  200.000000  200.000000  
mean     3.951015    2.475000    0.290000  
std      0.752553    1.079445    0.454901  
min      2.197000    1.000000    0.000000  
25%      3.434000    2.000000    0.000000  
50%      3.871000    2.000000    0.000000  
75%      4.382000    3.000000    1.000000  
max      7.419000    4.000000    1.000000  

[8 rows x 28 columns]

In [4]:
df.corr(method ='pearson').sort_values(by = 'churn', ascending=False).head()

tenure       age   address    income        ed    employ  \
churn    -0.376860 -0.287697 -0.260659 -0.090790  0.216112 -0.337969   
equip    -0.117102 -0.071357 -0.148977 -0.010741  0.488041 -0.174470   
equipmon -0.043274 -0.030402 -0.125212  0.000275  0.492999 -0.141651   
ebill    -0.099128 -0.048279 -0.172171 -0.041392  0.427315 -0.151965   
internet -0.164921 -0.078395 -0.191058  0.102809  0.552996 -0.250044   

             equip  callcard  wireless   longmon    ...        pager  \
churn     0.275284 -0.311451  0.174356 -0.292026    ...     0.124623   
equip     1.000000 -0.087051  0.386735 -0.097618    ...     0.308633   
equipmon  0.941065  0.026955  0.527573 -0.070876    ...     0.461458   
ebill     0.603133 -0.045058  0.321433 -0.124605    ...     0.288752   
internet  0.623509 -0.067146  0.343631 -0.223929    ...     0.266193   

          internet  callwait    confer     ebill   loglong   logtoll  \
churn     0.254838 -0.052885 -0.081361  0.254838 -0.336869 -0.070156   
equip     0.623509 -0.034021 -0.103499  0.603133 -0.113065 -0.027882   
equipmon  0.631338  0.104341  0.056846  0.602010 -0.062455  0.047387   
ebill     0.512987 -0.061492 -0.090542  1.000000 -0.133310  0.024784   
internet  1.000000  0.019419 -0.029911  0.512987 -0.202230  0.038008   

             lninc   custcat     churn  
churn    -0.117459  0.014839  1.000000  
equip     0.083494  0.174955  0.275284  
equipmon  0.095942  0.333664  0.255348  
ebill     0.039137  0.104775  0.254838  
internet  0.067611  0.160904  0.254838  

[5 rows x 28 columns]

In [5]:
# Features to array
X = np.asarray(df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X

array([[11., 33.,  7., ...,  5.,  5.,  0.],
       [33., 33., 12., ...,  2.,  0.,  0.],
       [23., 30.,  9., ...,  1.,  2.,  0.],
       ...,
       [ 6., 32., 10., ...,  1., 10.,  0.],
       [24., 30.,  0., ...,  4.,  5.,  0.],
       [61., 50., 16., ...,  2., 22.,  1.]])

In [6]:
# Target data type to int - required to sklearn LR
#Target to array
df['churn'] = df['churn'].astype('int')
y = np.asarray(df['churn'])
y

array([1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0])

In [7]:
# Normalizing Features
X = preprocessing.StandardScaler().fit(X).transform(X)

In [8]:
# Data Split 80/20
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=4)
print ('Train set:', X_train.shape,  y_train.shape)
print ('Test set:', X_test.shape,  y_test.shape)

Train set: (160, 7) (160,)
Test set: (40, 7) (40,)


In [9]:
# Modeling and Training
lr = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,y_train)

# Prediction and Probability
lr_pred = lr.predict(X_test)
lr_proba = lr.predict_proba(X_test)




# Evaluation

In [10]:
#Jaccard - binary - positive label = 0 (not churn)
jaccard = jaccard_score(y_test,lr_pred, pos_label=0)
jaccard

0.7058823529411765

In [11]:
# Compute confusion matrix
cnf_matrix = confusion_matrix(y_test, lr_pred, labels=[1,0])
np.set_printoptions(precision=2)
print (classification_report(y_test, lr_pred))
cnf_matrix

              precision    recall  f1-score   support

           0       0.73      0.96      0.83        25
           1       0.86      0.40      0.55        15

    accuracy                           0.75        40
   macro avg       0.79      0.68      0.69        40
weighted avg       0.78      0.75      0.72        40



array([[ 6,  9],
       [ 1, 24]], dtype=int64)

In [12]:
# Logloss
logloss = log_loss(y_test, lr_proba)

In [13]:
print('Results: Jaccard= ', jaccard,'F1 = 0.72', 'LogLoss=', logloss, 'for regularization = 0.01 and solver liblinear' )

Results: Jaccard=  0.7058823529411765 F1 = 0.72 LogLoss= 0.6017092478101185 for regularization = 0.01 and solver liblinear
